apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: students.esdevops.com
spec:
  group: esdevops.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
            status:
              type: object
              properties:
                eating:
                  type: boolean
                  default: true
                learning:
                  type: boolean
                  default: false
                playing:
                  type: boolean
                  default: false
                sleeping:
                  type: boolean
                  default: false
  scope: Namespaced
  names:
    plural: students
    singular: student
    kind: Student